name: dpil
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.0
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_keyboard_visibility: ^6.0.0
  cloud_firestore: ^4.14.0
  animate_do: ^3.3.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/

