name: dpil
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.0
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_keyboard_visibility: ^6.0.0
  cloud_firestore: ^4.14.0
  animate_do: ^3.3.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  location: ^5.0.3
  font_awesome_flutter: ^10.7.0
  slide_to_act: ^2.0.2
  intl: ^0.18.0
  geocoding: ^2.2.0
  flutter_barcode_scanner: ^2.0.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  month_year_picker: ^0.3.0+1 
  pdf: ^3.10.8
  printing: ^5.12.0
  flutter_email_sender: ^6.0.2
  path_provider: ^2.1.2
  calendar_date_picker2: ^0.5.5
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/fonts/robotoregular.ttf

fonts:
    - family: robotoregular
      fonts:
        - asset: assets/fonts/robotoregular.ttf

