export 'package:dpil/presentation/admin/adddouser/admin_adddouser.screen.dart';
export 'package:dpil/presentation/admin/addgenuser/admin_addgenuser.screen.dart';
export 'package:dpil/presentation/admin/addproduct/admin_addproduct.screen.dart';
export 'package:dpil/presentation/admin/addvendor/admin_addvendor.screen.dart';
export 'package:dpil/presentation/admin/dashboard/admin_dashboard.screen.dart';
export 'package:dpil/presentation/douser/dashboard/douser_dashboard.screen.dart';
export 'package:dpil/presentation/genuser/dashboard/genuser_dashboard.screen.dart';
export 'package:dpil/presentation/login/login.screen.dart';
export 'package:dpil/presentation/splash/splash.screen.dart';